#!/usr/bin/python

import dbus
from dbus.mainloop.glib import DBusGMainLoop
import gobject

import subprocess
import bluezutils

# ID of the Wiiboard
DEV_ID = '00_26_59_6B_AE_A3'
DEVID = '00:26:59:6B:AE:A3'

def connected(*args, **kwargs):
    dbus_message = args[1]
        
    if 'Connected' in dbus_message:
        if dbus_message['Connected'] == False:
            print 'Disconnected: ' + DEVID
        else:
            print "Connected: " + DEVID
            subprocess.call(["/usr/sbin/wiiboardnet", DEVID])
    else:
        print "Unsure: " + dbus_message

def main():
    dbus_loop = DBusGMainLoop()
    bus = dbus.SystemBus(mainloop=dbus_loop)

    # Figure out the path to the wiiboard
    path = bluezutils.find_adapter().object_path

    adapter = dbus.Interface(bus.get_object("org.bluez", path),"org.bluez.Adapter1")

    wiiboard = bus.get_object('org.bluez', path + '/dev_' + DEV_ID)
        
    wiiboard.connect_to_signal("PropertiesChanged", connected)

    print "Listening to " + DEVID + " for connection"
    
    loop = gobject.MainLoop()
    loop.run()
    
if __name__ == "__main__":
    main()
