#!/usr/bin/env python

import dbus
from dbus.mainloop.glib import DBusGMainLoop
import gobject

import subprocess
import bluezutils

# ID of the Wiiboard
DEV_ID = '00_26_59_6B_AE_A3'
DEVID = '00:26:59:6B:AE:A3'
StatusCount = 0

def connected(*args, **kwargs):
    for arg in args:
        print arg    

    if args[0] == "Connected":
        global StatusCount
        StatusCount = StatusCount + 1
        
        #For some reason, the connected/disconnected status gets sent twice, 
        #so this prevents the second one from doing anything.
        if StatusCount % 2 == 1:
            if args[1] == False:
                print 'Disconnected: ' + DEVID
            else:
                print "Connected: " + DEVID
                subprocess.call(["/usr/sbin/wiiboardnet", DEVID])
            
            StatusCount = 1
    else:
        print "Unsure: " + args[0]

def main():
    dbus_loop = DBusGMainLoop()
    bus = dbus.SystemBus(mainloop=dbus_loop)

    # Figure out the path to the wiiboard
    path = path = bluezutils.find_adapter().object_path

    adapter = dbus.Interface(bus.get_object("org.bluez", path),"org.bluez.Adapter1")

    wiiboard = bus.get_object('org.bluez', path + '/dev_' + DEV_ID)
        
    wiiboard.connect_to_signal("PropertiesChanged", connected)

    print "Listening to " + DEVID + " for connection"
    
    loop = gobject.MainLoop()
    loop.run()
    
if __name__ == "__main__":
    main()
